services:
  graph:
    image: ghcr.io/oxigraph/oxigraph@sha256:e68b3625743db4a4b18129a907ae36766f89bb6deeb8ab50d35685dbabe00b0e
    command:
      - serve-read-only
      - --location
      - /data
      - --bind
      - 0.0.0.0:7878
      - --union-default-graph
