#!/usr/bin/env bash
set -Eeuo pipefail

base=/home/user1106/financial-agent-v2
backup_root=${base}/shared/backups
incoming=${base}/incoming
pointer=${backup_root}/latest-data-api-cutover.txt
expected_release=financial-products-2026-08-24@ddb3d994a4a5115a75bed7efa9c4cd0f6655f95b0a49f3b0e3c01b2bf8301a38
journal=${1:-}
if [[ ${journal} == --latest ]]; then
  journal=$(tr -d '\r\n' <"${pointer}")
fi
journal=$(readlink -f -- "${journal}")
case "${journal}" in
  ${backup_root}/data-platform-v2-*/data-api-cutover-*/journal.env) ;;
  *) echo "RESUME_REFUSE_JOURNAL: ${journal}" >&2; exit 2 ;;
esac
test -f "${journal}" && test -O "${journal}" && test "$(stat -c '%a' "${journal}")" = 600

# Generated by the cutover script and owner-only. It contains no plaintext password.
# shellcheck disable=SC1090
source "${journal}"
for key in PROJECT POSTGRES_USER POSTGRES_DB API_PORT CURRENT_GRAPH NEXT_GRAPH RELEASE_DIR V2_API_IMAGE LOCK_FILE; do
  test -n "${!key+x}" || { echo "RESUME_JOURNAL_FAIL missing ${key}" >&2; exit 2; }
done
test "${PROJECT}" = financial-agent-prep
test "${LOCK_FILE}" = "${backup_root}/data-api-cutover.lock"
test "${NEXT_GRAPH}" = financial-agent-prep_oxigraph-next-2026-08-24-57c4edc
test -f "${incoming}/data_api_rollback.sh"
test -f "${incoming}/data_api_verify.sh"
test -f "${incoming}/data_api_watchdog.sh"
test -f "${incoming}/data_api_ack.sh"
test -f "${incoming}/compose.api-image.yaml"
test -f "${incoming}/compose.data-api-active.yaml"

exec 9>"${LOCK_FILE}"
flock -n 9 || { echo 'another data API cutover or rollback is active' >&2; exit 2; }
cd "${RELEASE_DIR}"
export COMPOSE_PROJECT_NAME="${PROJECT}" POSTGRES_USER POSTGRES_DB
export OXIGRAPH_NEXT_VOLUME="${NEXT_GRAPH}" DATA_API_IMAGE="${V2_API_IMAGE}"
psql=(docker compose exec -T db psql -v ON_ERROR_STOP=1 -U "${POSTGRES_USER}" -d "${POSTGRES_DB}")
psql_at=("${psql[@]}" -At -c)

canonical_count=$("${psql_at[@]}" "SELECT count(*) FROM pg_namespace WHERE nspname IN ('meta','raw','enriched','relations','vec','core')")
next_count=$("${psql_at[@]}" "SELECT count(*) FROM pg_namespace WHERE nspname IN ('meta_next','raw_next','enriched_next','relations_next','vec_next','core_next')")
prev_count=$("${psql_at[@]}" "SELECT count(*) FROM pg_namespace WHERE nspname IN ('meta_prev','raw_prev','enriched_prev','relations_prev','vec_prev','core_prev')")
failed_count=$("${psql_at[@]}" "SELECT count(*) FROM pg_namespace WHERE nspname IN ('meta_failed','raw_failed','enriched_failed','relations_failed','vec_failed','core_failed')")
test "${canonical_count}" = 6
test "${next_count}" = 0
test "${prev_count}" -ge 1 && test "${prev_count}" -le 5
test "${failed_count}" = 0
test -z "$(docker compose ps --status running -q api)"
docker image inspect "${V2_API_IMAGE}" >/dev/null
graph_id=$(docker compose ps -q graph)
test -n "${graph_id}" && test "$(docker inspect -f '{{.State.Running}}' "${graph_id}")" = true
test "$(docker inspect -f '{{range .Mounts}}{{if eq .Destination "/data"}}{{.Name}}{{end}}{{end}}' "${graph_id}")" = "${NEXT_GRAPH}"

record_phase() { printf 'PHASE=%q\n' "$1" >>"${journal}"; }
rollback_needed=1
on_error() {
  code=$?
  trap - ERR HUP INT TERM
  if [[ ${rollback_needed} == 1 ]]; then
    CUTOVER_LOCK_HELD=1 bash "${incoming}/data_api_rollback.sh" "${journal}" || exit 97
  fi
  exit "${code}"
}
trap on_error ERR
trap 'trap - ERR HUP INT TERM; CUTOVER_LOCK_HELD=1 bash "${incoming}/data_api_rollback.sh" "${journal}" || exit 97; exit 130' HUP INT TERM

record_phase resume_normalizing_rollback_schemas
"${psql[@]}" <<'SQL'
DO $do$
DECLARE
  base_name text;
  bases text[] := ARRAY['meta','raw','enriched','relations','vec','core'];
BEGIN
  FOREACH base_name IN ARRAY bases LOOP
    IF to_regnamespace(base_name || '_prev') IS NULL THEN
      EXECUTE format('CREATE SCHEMA %I', base_name || '_prev');
      EXECUTE format('COMMENT ON SCHEMA %I IS %L', base_name || '_prev', 'empty rollback placeholder for a schema absent before V2 cutover');
    END IF;
  END LOOP;
END
$do$;
SQL
test "$("${psql_at[@]}" "SELECT count(*) FROM pg_namespace WHERE nspname IN ('meta_prev','raw_prev','enriched_prev','relations_prev','vec_prev','core_prev')")" = 6

record_phase resume_revoking_previous_schemas
"${psql[@]}" <<'SQL'
DO $do$
DECLARE
  schema_name text;
BEGIN
  FOR schema_name IN
    SELECT nspname FROM pg_namespace
    WHERE nspname IN ('meta_prev','raw_prev','enriched_prev','relations_prev','vec_prev','core_prev')
  LOOP
    EXECUTE format('REVOKE ALL ON SCHEMA %I FROM agent_reader', schema_name);
    EXECUTE format('REVOKE ALL ON ALL TABLES IN SCHEMA %I FROM agent_reader', schema_name);
    EXECUTE format('REVOKE ALL ON ALL SEQUENCES IN SCHEMA %I FROM agent_reader', schema_name);
    EXECUTE format('REVOKE ALL ON ALL FUNCTIONS IN SCHEMA %I FROM agent_reader', schema_name);
  END LOOP;
END
$do$;
ALTER ROLE agent_reader NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
SQL

record_phase resume_api_starting
OXIGRAPH_ACTIVE_VOLUME="${NEXT_GRAPH}" DATA_API_IMAGE="${V2_API_IMAGE}" \
  docker compose -f compose.yaml -f deploy/compose.graph-pointer.yaml -f "${incoming}/compose.api-image.yaml" \
  up -d --no-build api

record_phase resume_verifying
bash "${incoming}/data_api_verify.sh"

mkdir -p artifacts/runtime
override_tmp=compose.override.yaml.resume-tmp
cp "${incoming}/compose.data-api-active.yaml" "${override_tmp}"
mv "${override_tmp}" compose.override.yaml
runtime_tmp=artifacts/runtime/data-api-active.env.resume-tmp
printf 'STATUS=active\nOXIGRAPH_ACTIVE_VOLUME=%s\nDATA_API_IMAGE=%s\n' "${NEXT_GRAPH}" "${V2_API_IMAGE}" >"${runtime_tmp}"
mv "${runtime_tmp}" artifacts/runtime/data-api-active.env
record_phase resume_cutover_complete
printf 'STATUS=passed\nFINISHED_AT=%q\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" >>"${journal}"

ack_file=$(dirname "${journal}")/consumer-ack
armed_file=$(dirname "${journal}")/watchdog-armed
nohup env WATCHDOG_DELAY_SECONDS=300 bash "${incoming}/data_api_watchdog.sh" "${journal}" \
  >"$(dirname "${journal}")/watchdog.log" 2>&1 </dev/null 9>&- &
watchdog_pid=$!
for _ in $(seq 1 50); do
  [[ -f ${armed_file} ]] && break
  sleep 0.1
done
test -f "${armed_file}" && kill -0 "${watchdog_pid}"
printf 'WATCHDOG_PID=%s\nCONSUMER_ACK=%q\n' "${watchdog_pid}" "${ack_file}" >>"${journal}"
rollback_needed=0
trap - ERR HUP INT TERM
printf 'DATA API CUTOVER RESUME PASS: release=%s graph=%s\n' "${expected_release}" "${NEXT_GRAPH}"
printf 'DATA_API_CUTOVER_JOURNAL=%s\n' "${journal}"
printf 'DATA_API_CUTOVER_ACK=%s\n' "${ack_file}"
